import './globals.css'
import { Inter } from 'next/font/google';
import Navbar from '@/component/navbar/Navbar';
import Footer from '@/component/footer/Footer';
import { ThemeContextProvider } from '@/context/ThemeContext';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Next.js Blog App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/*<AuthProvider>*/}
          <ThemeContextProvider>
          <div className='container'>
          <div className='wrapper'>
            <Navbar />
            {children}
            <Footer />
          </div>
        </div>
          </ThemeContextProvider>
        
        {/*</AuthProvider>*/}
      </body>
    </html>
  )
}
